export const dummyUsers = [
  {
    fullName: "Nitish Kumar",
    email: "nitish@gmail.com",
    phone: "9257895789",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Amit Sharma",
    email: "amit.sharma@gmail.com",
    phone: "9123456781",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Rahul Verma",
    email: "rahul.verma@gmail.com",
    phone: "9123456782",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Priya Singh",
    email: "priya.singh@gmail.com",
    phone: "9123456783",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Ankit Patel",
    email: "ankit.patel@gmail.com",
    phone: "9123456784",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Sneha Gupta",
    email: "sneha.gupta@gmail.com",
    phone: "9123456785",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Rohit Yadav",
    email: "rohit.yadav@gmail.com",
    phone: "9123456786",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Neha Mishra",
    email: "neha.mishra@gmail.com",
    phone: "9123456787",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Vikas Tiwari",
    email: "vikas.tiwari@gmail.com",
    phone: "9123456788",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Pooja Dubey",
    email: "pooja.dubey@gmail.com",
    phone: "9123456789",
    password: "qwerty",
    userType: "regular",
  },

  {
    fullName: "Sandeep Chauhan",
    email: "sandeep.chauhan@gmail.com",
    phone: "9234567890",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Ritu Saxena",
    email: "ritu.saxena@gmail.com",
    phone: "9234567891",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Karan Malhotra",
    email: "karan.malhotra@gmail.com",
    phone: "9234567892",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Deepak Joshi",
    email: "deepak.joshi@gmail.com",
    phone: "9234567893",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Aarti Pandey",
    email: "aarti.pandey@gmail.com",
    phone: "9234567894",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Manish Gupta",
    email: "manish.gupta@gmail.com",
    phone: "9234567895",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Shivam Singh",
    email: "shivam.singh@gmail.com",
    phone: "9234567896",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Riya Kapoor",
    email: "riya.kapoor@gmail.com",
    phone: "9234567897",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Aditya Raj",
    email: "aditya.raj@gmail.com",
    phone: "9234567898",
    password: "qwerty",
    userType: "regular",
  },
  {
    fullName: "Kavita Sharma",
    email: "kavita.sharma@gmail.com",
    phone: "9234567899",
    password: "qwerty",
    userType: "regular",
  },
];
